# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AyiCzwNTsbLHkxIJOCXC-nHgeyDwYDvL
"""

# Bismillah dulu Ygy
!pip install scikit-learn pandas numpy matplotlib seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Intinya sih begini
from sklearn.linear_model import LinearRegression   # model regresi linear
from sklearn.model_selection import train_test_split # buat bagi data
from sklearn.metrics import mean_squared_error, r2_score  # buat nilai rapor

print("=" * 55)
print("  SCIKIT-LEARN LEVEL 1: REGRESI LINEAR")
print("  Dataset: House Prices (Kaggle)")
print("=" * 55)

df = pd.read_csv("train.csv")

print(f"\n✅ Data berhasil dimuat!")
print(f"   Jumlah baris  : {df.shape[0]} rumah")
print(f"   Jumlah kolom  : {df.shape[1]} fitur")

# Lihat 5 baris pertama untuk kenalan sama datanya
print("\n--- 5 Baris Pertama Data ---")
print(df.head())

# Lihat info umum: tipe data, ada nilai kosong ga?
print("\n--- Info Data ---")
print(df.info())

# Statistik dasar: rata-rata, min, max, dll
print("\n--- Statistik Dasar ---")
print(df.describe())

# STEP 3: Pilih fitur (X) dan target (y)
# --------------------------------------------------
# Buat Level 1 ini, mau pakai fitur numerik yang simpel dulu.


# Fitur-fitur yang mau kita pakai untuk prediksi harga:
fitur_yang_dipilih = [
    "GrLivArea",    # Luas area tinggal (sqft)
    "BedroomAbvGr", # Jumlah kamar tidur
    "FullBath",     # Jumlah kamar mandi lengkap
    "GarageCars",   # Kapasitas garasi (jumlah mobil)
    "OverallQual",  # Kualitas keseluruhan rumah (skala 1-10)
    "YearBuilt",    # Tahun dibangun
    "TotalBsmtSF",  # Luas basement
]

# Target yang mau kita prediksi:
target = "SalePrice"  # Harga jual rumah

print(f"\n--- Fitur yang Kita Pakai ---")
for i, f in enumerate(fitur_yang_dipilih, 1):
    print(f"   {i}. {f}")
print(f"\n   Target prediksi: {target}")

# Ambil kolom yang kita mau
X = df[fitur_yang_dipilih]
y = df[target]

print(f"\n✅ Fitur (X) shape : {X.shape}")
print(f"   Target (y) shape: {y.shape}")

# STEP 4: Cek & handel nilai kosong (NaN)
# --------------------------------------------------
print("\n--- Cek Nilai Kosong di Fitur ---")
print(X.isnull().sum())

# Kalau ada nilai kosong, kita isi dengan nilai median kolom itu
# (cara paling simpel untuk level pemula)
X = X.fillna(X.median())

print("\n✅ Nilai kosong sudah diisi dengan median")

# STEP 5: Bagi data → Training set & Testing set
# --------------------------------------------------
# Gass bagi data jadi 2:
#   - 80% untuk LATIHAN model (training set)
#   - 20% untuk UJIAN model  (testing set)
# random_state=42 → supaya hasilnya sama tiap kali dijalankan
# (angka 42 tidak ada yang spesial, cuma konvensi umum)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,    # 20% untuk testing
    random_state=42
)

print(f"\n--- Pembagian Data ---")
print(f"   Total data      : {len(X)} baris")
print(f"   Data latihan    : {len(X_train)} baris (80%)")
print(f"   Data ujian      : {len(X_test)} baris  (20%)")

# STEP 6: Buat & latih model (kondisi udah laper,sabar perutku)
# --------------------------------------------------
# Ini bagian ajaibnya scikit-learn — cukup 2 baris!

model = LinearRegression()  # buat model baru (masih kosong)
model.fit(X_train, y_train) # latih model pakai data training

print("\n✅ Model selesai dilatih!")

# Lihat koefisien tiap fitur
print("\n--- Koefisien Model (pengaruh tiap fitur ke harga) ---")
for fitur, koef in zip(fitur_yang_dipilih, model.coef_):
    arah = "naik" if koef > 0 else "turun"
    print(f"   {fitur:20s}: {koef:+10.2f}  → harga {arah}")

print(f"\n   Intercept (nilai dasar): {model.intercept_:,.2f}")

# STEP 7: Prediksi & Evaluasi **Mwahahahaha
# --------------------------------------------------
# Pakai model yang sudah dilatih untuk prediksi data test
y_pred = model.predict(X_test)

# Hitung metrik evaluasi
mse  = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2   = r2_score(y_test, y_pred)

print("\n" + "=" * 55)
print("  RAPOR MODEL")
print("=" * 55)
print(f"\n  RMSE  : ${rmse:,.0f}")
print(f"  (Rata-rata selisih prediksi vs harga asli)")
print(f"\n  R²    : {r2:.4f} ({r2*100:.1f}%)")
print(f"  (Seberapa baik model menjelaskan variasi data)")
print(f"  → R² = 1.0 berarti sempurna, R² = 0 berarti payah")

# Interpretasi R²
if r2 >= 0.8:
    komentar = "Bagus banget! Model cukup akurat."
elif r2 >= 0.6:
    komentar = "Lumayan! Tapi masih bisa ditingkatkan."
else:
    komentar = "Perlu perbaikan. Coba tambah lebih banyak fitur."
print(f"\n  Kesimpulan: {komentar}")

# STEP 8: Gassin Lihat beberapa baik hasil prediksi
# --------------------------------------------------
print("\n--- Perbandingan Harga Asli vs Prediksi (10 contoh) ---")
print(f"{'No':>3}  {'Harga Asli':>15}  {'Prediksi':>15}  {'Selisih':>12}")
print("-" * 50)

hasil = pd.DataFrame({
    "Harga Asli": y_test.values,
    "Prediksi"  : y_pred.round(0)
}).head(10)

for i, row in hasil.iterrows():
    asli     = row["Harga Asli"]
    prediksi = row["Prediksi"]
    selisih  = prediksi - asli
    tanda    = "+" if selisih >= 0 else ""
    print(f"  {list(hasil.index).index(i)+1:>1}.  ${asli:>12,.0f}  ${prediksi:>12,.0f}  {tanda}${selisih:>10,.0f}")

# STEP 9: Visualisasi Siapa yang tidak suka??
# --------------------------------------------------
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle("Scikit-Learn Level 1 — Regresi Linear: House Prices", fontsize=14)

# --- Grafik 1: Harga Asli vs Prediksi ---
ax1 = axes[0]
ax1.scatter(y_test, y_pred, alpha=0.5, color="steelblue", s=20)
# garis ideal: kalau prediksi sempurna, semua titik ada di sini
min_val = min(y_test.min(), y_pred.min())
max_val = max(y_test.max(), y_pred.max())
ax1.plot([min_val, max_val], [min_val, max_val], "r--", lw=2, label="Prediksi sempurna")
ax1.set_xlabel("Harga Asli ($)")
ax1.set_ylabel("Harga Prediksi ($)")
ax1.set_title("Harga Asli vs Prediksi")
ax1.legend()

# --- Grafik 2: Distribusi Error (selisih) ---
ax2 = axes[1]
error = y_test.values - y_pred
ax2.hist(error, bins=50, color="coral", edgecolor="white")
ax2.axvline(x=0, color="red", linestyle="--", lw=2)
ax2.set_xlabel("Error (Asli - Prediksi)")
ax2.set_ylabel("Jumlah")
ax2.set_title("Distribusi Error Prediksi")

# --- Grafik 3: Korelasi Fitur dengan Harga ---
ax3 = axes[2]
korelasi = df[fitur_yang_dipilih + [target]].corr()[target].drop(target).sort_values()
colors   = ["#e74c3c" if x < 0 else "#2ecc71" for x in korelasi]
ax3.barh(korelasi.index, korelasi.values, color=colors)
ax3.set_xlabel("Korelasi dengan Harga Jual")
ax3.set_title("Pengaruh Tiap Fitur ke Harga")
ax3.axvline(x=0, color="black", lw=0.8)

plt.tight_layout()
plt.savefig("level1_hasil.png", dpi=150, bbox_inches="tight")
plt.show()
print("\n✅ Grafik disimpan sebagai: level1_hasil.png")

# STEP 10: Coba prediksi rumah baru (orang kelaparan lagi gabut)
# --------------------------------------------------
print("\n" + "=" * 55)
print("  BONUS: PREDIKSI RUMAH BARU")
print("=" * 55)

# Misal kamu mau prediksi harga rumah dengan spesifikasi ini:
rumah_baru = pd.DataFrame([{
    "GrLivArea"   : 1500,   # luas 1500 sqft
    "BedroomAbvGr": 3,      # 3 kamar tidur
    "FullBath"    : 2,      # 2 kamar mandi
    "GarageCars"  : 2,      # garasi 2 mobil
    "OverallQual" : 7,      # kualitas 7/10
    "YearBuilt"   : 2005,   # dibangun tahun 2005
    "TotalBsmtSF" : 800,    # basement 800 sqft
}])

harga_prediksi = model.predict(rumah_baru)[0]

print(f"\n  Spesifikasi rumah:")
for k, v in rumah_baru.iloc[0].items():
    print(f"    {k:20s}: {v}")

print(f"\n  Prediksi harga  : ${harga_prediksi:,.0f}")

print("\n" + "=" * 55)
print("  SELAMAT! Level 1 selesai sayangkuuuh.")
print("  Langkah selanjutnya: Level 2 — Klasifikasi (fighting)")
print("=" * 55)